# Shrink only: names stay intact, so crash traces stay readable and code that
# looks members up by name (Gson, protobuf-lite, JNI, WebView) keeps working.
-dontobfuscate
# Optimization merges classes, so traces name the wrong class even without renaming.
-dontoptimize

-keepattributes Signature,*Annotation*,InnerClasses,EnclosingMethod,SourceFile,LineNumberTable

# Room instantiates generated *_Impl databases (WorkManager's included) by reflection;
# Room 2.6.1's runtime jar ships no rule for it.
-keep class * extends androidx.room.RoomDatabase { <init>(); }

# No consumer rules shipped, and their native code reaches Java members by name,
# which R8 cannot see.
-keep class com.google.ai.edge.litertlm.** { *; }
-keep class com.google.ai.edge.litert.** { *; }
-keep class org.tensorflow.lite.** { *; }
-keep class com.google.mediapipe.** { *; }

-keepclassmembers class * extends com.google.protobuf.GeneratedMessageLite { <fields>; }

# Gson populates these reflectively. The classes themselves must be kept, not just their
# fields: R8 full mode drops generic Signatures on unkept classes, so List<AllowedModel>
# deserializes as a list of maps.
-keep class com.google.ai.edge.gallery.data.** { <fields>; <init>(...); }
-keep class com.google.ai.edge.gallery.relay.model.HfCardEntry { <fields>; <init>(...); }

# Firebase ComponentDiscovery instantiates registrars (ML Kit's included) by reflection.
-keep class * implements com.google.firebase.components.ComponentRegistrar { <init>(); }

-keepclassmembers class * { @android.webkit.JavascriptInterface <methods>; }

# The Android Main dispatcher is registered through META-INF/services, so R8 sees no caller and
# strips it; the app then dies on first Dispatchers.Main use with "Module with the Main dispatcher
# is missing".
-keep class kotlinx.coroutines.android.AndroidDispatcherFactory { *; }
-keep class kotlinx.coroutines.android.AndroidExceptionPreHandler { *; }
-keep class * implements kotlinx.coroutines.internal.MainDispatcherFactory { *; }
-keep class * implements kotlinx.coroutines.CoroutineExceptionHandler { *; }
-keepclassmembers class kotlinx.coroutines.** { volatile <fields>; }

# LiteRT-LM reads ToolSet classes by Kotlin reflection, which needs their @Metadata; R8 sees no caller.
-keep class * implements com.google.ai.edge.litertlm.ToolSet { *; }
-keepclassmembers class * { @com.google.ai.edge.litertlm.Tool <methods>; }
-keep class kotlin.Metadata { *; }

-keep class com.google.ai.edge.gallery.worker.DownloadWorker {
  public <init>(android.content.Context, androidx.work.WorkerParameters);
}

# Generated by R8 (missing_rules.txt): MediaPipe profiler/template protos that are
# not shipped, and a JVM-only debugger check in Ktor.
-dontwarn com.google.mediapipe.proto.CalculatorProfileProto$CalculatorProfile
-dontwarn com.google.mediapipe.proto.GraphTemplateProto$CalculatorGraphTemplate
-dontwarn java.lang.management.ManagementFactory
-dontwarn java.lang.management.RuntimeMXBean
